kubectl delete --all deployments
kubectl delete services rabbit-deployment
kubectl delete services gateway-deployment
kubectl delete services frontend-deployment
kubectl delete configmap user-db-config
kubectl delete configmap app-db-config
kubectl delete persistentvolumeclaim user-db-pv-claim
kubectl delete persistentvolumeclaim app-db-pv-claim
kubectl delete persistentvolume user-db-pv-volume
kubectl delete persistentvolume app-db-pv-volume