kind: PersistentVolume
apiVersion: v1
metadata:
  name: user-db-pv-volume
  labels:
    type: local
    app: user-db
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/kamil/Pulpit/agh/ask/db/user"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: user-db-pv-claim
  labels:
    app: user-db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi